//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestRessourceServer.Models
{
    using System.Collections.Generic;
    
    public partial class Director
    {
        public Director()
        {
            this.Movie = new HashSet<Movie>();
        }
    
        public int DirectorId { get; set; }
        public string Firstname { get; set; }
        public string Lastname { get; set; }
    
        public virtual ICollection<Movie> Movie { get; set; }
    }
}
