//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestRessourceServer.Models
{
    using System;

    public partial class Movie
    {
        public int MovieId { get; set; }
        public string Title { get; set; }
        public Nullable<int> DirectorId { get; set; }
    
        public virtual Director Director { get; set; }
    }
}
