//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestRessourceServer.Models
{
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OAuth2TestDbEntities : DbContext
    {
        public OAuth2TestDbEntities()
            : base("name=OAuth2TestDbEntities")
        {
            Configuration.ProxyCreationEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Director> Director { get; set; }
        public DbSet<Movie> Movie { get; set; }
    }
}
